version: '3.6'

services:
  builder:
    image: lslio/nginx-php-fpm
    build: 
      context: ../
      args:
        VERSION_ALPINE: 3.13.7
    entrypoint: /bin/true

  example:
    image: lslio/nginx-php-fpm-example
    build: ./
    volumes:
      - .:/www
    ports:
      - "80:80"
    environment:
      SERVER_NAME: "example.localhost"

